CREATE TABLE [dbo].[Product]
(
	[Id] INT NOT NULL IDENTITY,
	[ProductName] NVARCHAR(50) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[RetailPrice] MONEY NOT NULL,
	[CreateDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[LastModified] DATETIME2 NOT NULL DEFAULT GETUTCDATE()

	CONSTRAINT PK_ProductId PRIMARY KEY (Id)
)
