CREATE TABLE [dbo].[SaleDetail]
(
	[Id] INT NOT NULL IDENTITY,
	[SaleId] INT NOT NULL,
	[ProductId] NVARCHAR(50) NOT NULL,
	[Quantity] INT NOT NULL DEFAULT 1,
	[PurchasePrice] MONEY NOT NULL,
	[Tax] MONEY NOT NULL DEFAULT 0,
	
	CONSTRAINT PK_SaleDetailId PRIMARY KEY (Id)	
)
